title: "VeinSint | OSINT Analyst"
description: "Портфолио OSINT-аналитика"
remote_theme: jekyll/minima@HEAD

minima:
  skin: dark
  date_format: "%d.%m.%Y"

header_pages:
  - cases.md
  - methodology.md
  - tools.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
